### PR TITLE
game over function complete

### PR DESCRIPTION
**Pull request by bklee26**
Finished the game_over function

### CODE REVIEW

**Comment by RoelYoon** [comment]
@bklee26 please remove unnecessary files (a.out & code.cpp) from the repository. The code looks fine.

**Comment by bklee26** [comment]
@RoelYoon Done

**Comment by RoelYoon** [comment]
@bklee26 the issue seems unresolved. Please check again.

**Comment by bklee26** [comment]
@RoelYoon Done, please check again.

**Pull request merged**
